config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :likes
    end
  end
  resources :posts
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :horse_name, presence: true, length: { maximum: 20 }
  validates :post_comment, presence: true, length: { maximum: 100 }
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :fav_posts, through: :favorites, source: :post
  
  def like(post)
    favorites.find_or_create_by(post_id: post.id)
  end
  
  def unlike(post)
   favorite = favorites.find_by(post_id: post.id)
   favorite.destroy if favorite
  end
  
  def like?(post)
    self.fav_posts.include?(post)
  end
  
  def feed_posts
    Post.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   include SessionsHelper
  
  def counts(user)
    @count_posts = user.posts.count
    @count_favorites = user.favorites.count
  end
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    post = Post.find(params[:post_id])
    current_user.like(post)
    flash[:success] = 'お気に入りしました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    post = Post.find(params[:post_id])
    current_user.unlike(post)
    flash[:success] = 'お気に入り解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  before_action :correct_user, only: [:destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @sinchaku_posts = Post.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end
  
  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '投稿に成功しました。' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '編集しました。' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :horse_name, :post_comment, :user_id, :image)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      unless @post
        redirect_to root_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @posts = Post.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @sinchaku_posts = Post.order(created_at: :desc).limit(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :require_user_logged_in, only: [:index, :show]

  # GET /users/1
  # GET /users/1.json
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @posts = current_user.feed_posts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  # GET /users/new
  def new
    @user = User.new
  end


  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    
      if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
      else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
      end
  end
  
  def likes
    @user = User.find(params[:id])
    @fav_posts = @user.fav_posts.page(params[:page])
    counts(@user)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_fav_button.html.erb
<% if current_user.like?(post) %>

<%= form_with(model: current_user.favorites.find_by(post_id: post.id), local: true, method: :delete) do |f| %>

      
<%= hidden_field_tag :post_id, post.id %>
      
<%= f.submit 'お気に入り解除', class: 'btn btn-warning' %>

<% end %>

<% else %>

<%= form_with(model: current_user.favorites.build, local: true) do |f| %>

<%= hidden_field_tag :post_id, post.id %>

<%= f.submit 'お気に入り', class: 'btn btn-info' %>

<% end %>

<% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>

  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      
<% model.errors.full_messages.each do |message| %>

        <li>
<%= message %>
</li>
      
<% end %>

    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

  <div class="alert alert-
<%= message_type %>
">
<%= message %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">PhotoUma</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
<%= link_to new_post_path, class: 'nav-link' do %>
<i class="far fa-image fa-2x"></i>写真投稿
<% end %>
</li>
<li class="nav-item">
<%= link_to posts_path, class: 'nav-link' do %>
<i class="far fa-images fa-2x"></i>写真一覧
<% end %>
</li>
      </ul>
      <ul class="navbar-nav">
        
<% if logged_in? %>


       <li class="nav-item">
<%= link_to 'マイページ', user_path(current_user), class: 'nav-link' %>
</li>

         <li class="nav-item">
<%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
</li>


<% else %>
       <li class="nav-item">
<%= link_to 'ユーザー登録', signup_path, class: 'nav-link' %>
</li>
         <li class="nav-item">
<%= link_to 'ログイン', login_path, class: 'nav-link' %>
</li>
<% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PhotoUma</title>
    
<%= csrf_meta_tags %>

    
<%= csp_meta_tag %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    
<%= render 'layouts/navbar' %>


    <div class="container">
      
<%= render 'layouts/flash_messages' %>


      
<%= yield %>

    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :horse_name %>
    <%= form.text_field :horse_name %>
  </div>
  
  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :post_comment %>
    <%= form.text_area :post_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<ul class="list-inline">

<% posts.each do |post| %>

<%= link_to image_tag(post.image.thumb.url), post_path(post.id) %>

<% end %>

<%= paginate posts %>
</ul>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h3>新着</h3>
<div class="row row-eq-height">
<% @sinchaku_posts.each do |post| %>

<div class="col-md-2">
<div class="card-deck">
  <div class="card">
<%= image_tag post.image.thumb.url, class:'card-img-top', class:'img-thumbnail' %>
    <div class="card-body">
      <%= link_to 'Show', post_path(post) %>
    <% if current_user == post.user %>
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </div>
  </div>
</div>
</div>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Horse name:</strong>
  <%= @post.horse_name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @post.image.url %>
</p>

<p>
  <strong>Post comment:</strong>
  <%= @post.post_comment %>
</p>

<%= render 'favorites/fav_button', post: @post %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/toppages/index.html.erb
<% if logged_in? %>

  <p>ログイン完了ユーザ: 
<%= current_user.name %>
</p>

<h3>お気に入りランキング</h3>
<div class="row row-eq-height">
<% @all_ranks.each.with_index(1) do |post, i| %>
<div class="col-md-2">
<div class="card-deck">
  <div class="card">
    <%= "第#{i}位" %>
<%= image_tag post.image.thumb.url, class:'card-img-top', class:'img-fluid' %>
    <div class="card-body">
      <%= link_to 'Show', post_path(post) %>
    <% if current_user == post.user %>
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </div>
  </div>
</div>
</div>
<% end %>
</div>

<br>
<br>

<h3>新着</h3>
<div class="row row-eq-height">
<% @sinchaku_posts.each do |post| %>

<div class="col-md-2">
<div class="card-deck">
  <div class="card">
<%= image_tag post.image.thumb.url, class:'card-img-top', class:'img-thumbnail' %>
    <div class="card-body">
      <%= link_to 'Show', post_path(post) %>
    <% if current_user == post.user %>
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </div>
  </div>
</div>
</div>
<% end %>
</div>


<% else %>

<div class="center jumbotron">
  <div class="text-center">
    <h1>Welcome to the PhotoUma</h1>
    <%= link_to 'ユーザー登録', signup_path, class: 'btn btn-lg btn-primary' %>

  </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'ユーザーページ', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/likes.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      
      <li class="nav-item"><a href="
<%= user_path(@user.id) %>
" class="nav-link
<%= 'active' if current_page?(user_path(@user.id)) %>
">自分の投稿
<span class="badge badge-secondary">
<%= @count_posts %>
</span></a></li>
      
      <li class="nav-item"><a href="
<%= likes_user_path(@user.id) %>
" class="nav-link
<%= 'active' if current_page?(likes_user_path(@user.id)) %>
">お気に入り
<span class="badge badge-secondary">
<%= @count_favorites %>
</span></a></li>

    </ul>
    <%= render 'posts/posts', posts: @fav_posts %>
</div>



<%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    
<%= form_with(model: @user, local: true) do |f| %>

      
      <div class="form-group">
        
<%= f.label :name, 'ユーザーネーム' %>

        
<%= f.text_field :name, class: 'form-control' %>

      </div>

      <div class="form-group">
        
<%= f.label :email, 'メール' %>

        
<%= f.email_field :email, class: 'form-control' %>

      </div>

      <div class="form-group">
        
<%= f.label :password, 'パスワード' %>

        
<%= f.password_field :password, class: 'form-control' %>

      </div>

      <div class="form-group">
        
<%= f.label :password_confirmation, 'パスワード確認' %>

        
<%= f.password_field :password_confirmation, class: 'form-control' %>

      </div>

      
<%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>

    
<% end %>

  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      
      <li class="nav-item"><a href="
<%= user_path(@user.id) %>
" class="nav-link
<%= 'active' if current_page?(user_path(@user.id)) %>
">自分の投稿
<span class="badge badge-secondary">
<%= @count_posts %>
</span></a></li>
      
      <li class="nav-item"><a href="
<%= likes_user_path(@user.id) %>
" class="nav-link
<%= 'active' if current_page?(likes_user_path(@user.id)) %>
">お気に入り
<span class="badge badge-secondary">
<%= @count_favorites %>
</span></a></li>
</ul>
<%= render 'posts/posts', posts: @posts %>
    
</div>



<%= link_to 'Back', root_path %>